name = "MITgcm"
uuid = "dce5fa8e-68ce-4431-a242-9469c69627a0"
authors = ["gaelforget <gforget@mit.edu>"]
version = "0.5.12"

[deps]
ClimateModels = "f6adb021-9183-4f40-84dc-8cea6f651bb0"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dataverse = "9c0b9be8-e31e-490f-90fe-77697562404d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FortranFiles = "c58ffaec-ab22-586d-bfc5-781a99fd0b10"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
MeshArrays = "cb8c808f-1acf-59a3-9d2b-6e38d009f683"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"

[extensions]
MITgcmNetCDFExt = ["NetCDF"]

[compat]
ClimateModels = "0.3"
DataDeps = "0.7"
Dataverse = "0.2"
FortranFiles = "0.6"
Glob = "1"
MeshArrays = "0.4"
NetCDF = "0.11, 0.12"
Scratch = "1"
SparseArrays = "1"
Statistics = "1"
StyledStrings = "1"
julia = "^1.9"
